/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankTransactionDto } from './bankTransactionDto';


export interface ApiResponseDtoOfBankTransactionDto { 
    success?: boolean;
    message?: string | null;
    data?: BankTransactionDto;
    errors?: Array<string> | null;
}

