/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseCategoryDto } from './expenseCategoryDto';


/**
 * Generic API response wrapper
 */
export interface ApiResponseDtoOfExpenseCategoryDto { 
    /**
     * Indicates if the request was successful
     */
    success?: boolean;
    /**
     * Response message
     */
    message?: string | null;
    /**
     * Response data
     */
    data?: ExpenseCategoryDto | null;
    /**
     * Error details if any
     */
    errors?: Array<string> | null;
}

