/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for calculating shipping fee
 */
export interface CalculateShippingDto { 
    province: string;
    postalCode?: string | null;
    weight?: number | null;
}

