/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for creating a review
 */
export interface CreateReviewDto { 
    rating: number;
    title?: string | null;
    comment?: string | null;
}

