/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateErpSalesOrderItemDto } from './createErpSalesOrderItemDto';


export interface CreateErpSalesOrderDto { 
    branchId: number;
    customerId?: number | null;
    customerName?: string | null;
    customerPhone?: string | null;
    customerAddress?: string | null;
    customerTaxId?: string | null;
    orderDate: string;
    orderType: string;
    status?: string;
    discountPercentage?: number | null;
    discountAmount?: number | null;
    vatEnabled?: boolean;
    vatPercentage?: number;
    depositAmount?: number | null;
    deliveryAppointmentDate?: string | null;
    deliveryStatus?: string | null;
    productStatus?: string | null;
    notes?: string | null;
    internalNotes?: string | null;
    createdBy?: number | null;
    items: Array<CreateErpSalesOrderItemDto>;
}

