/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDeliveryDto { 
    branchId: number;
    ecommerceOrderId?: number | null;
    erpSalesOrderId?: number | null;
    scheduledDate: string;
    driverId?: number | null;
    vehicleNumber?: string | null;
    deliveryAddress: string;
    contactPerson?: string | null;
    contactPhone?: string | null;
    notes?: string | null;
    createdBy?: number | null;
}

