/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateErpSalesPaymentDto { 
    salesOrderId: number;
    branchId: number;
    paymentDate: string;
    paymentType: string;
    amount: number;
    paymentMethod?: string | null;
    bankName?: string | null;
    accountNumber?: string | null;
    transferDate?: string | null;
    slipUrl?: string | null;
    notes?: string | null;
    createdBy?: number | null;
}

