/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemDto } from './orderItemDto';


/**
 * DTO for detailed order information
 */
export interface OrderDetailDto { 
    id?: number;
    orderNumber?: string;
    userId?: number | null;
    status?: string;
    paymentStatus?: string;
    paymentMethod?: string | null;
    invoiceType?: string | null;
    paymentSlipUrl?: string | null;
    subtotal?: number;
    discountAmount?: number;
    couponCode?: string | null;
    shippingFee?: number;
    taxAmount?: number;
    totalAmount?: number;
    shippingFullName?: string | null;
    shippingPhone?: string | null;
    shippingEmail?: string | null;
    shippingAddressLine1?: string | null;
    shippingAddressLine2?: string | null;
    shippingDistrict?: string | null;
    shippingProvince?: string | null;
    shippingPostalCode?: string | null;
    shippingCountry?: string | null;
    shippingMethod?: string | null;
    shippingTrackingNumber?: string | null;
    estimatedDeliveryDate?: string | null;
    actualDeliveryDate?: string | null;
    customerNotes?: string | null;
    adminNotes?: string | null;
    items?: Array<OrderItemDto>;
    orderedAt?: string | null;
    paidAt?: string | null;
    shippedAt?: string | null;
    deliveredAt?: string | null;
    cancelledAt?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}

