/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GalleryImageDto } from './galleryImageDto';


export interface PaginatedResponseDtoOfGalleryImageDto { 
    items?: Array<GalleryImageDto> | null;
    page?: number;
    pageSize?: number;
    totalItems?: number;
    totalPages?: number;
    readonly hasPreviousPage?: boolean;
    readonly hasNextPage?: boolean;
}

