/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryRecordDto } from './salaryRecordDto';


export interface PayrollCalculationResponseDto { 
    month?: number;
    year?: number;
    totalEmployees?: number;
    totalNetSalary?: number;
    salaryRecords?: Array<SalaryRecordDto> | null;
    errors?: Array<string> | null;
}

