/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PhoneAllowanceUpdateDto { 
    periodMonth?: number;
    periodYear?: number;
    amount?: number;
    actualUsage?: number | null;
    maxAllowance?: number | null;
    billAttachment?: string | null;
    notes?: string | null;
}

