/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PhoneAllowanceDto { 
    id?: number;
    employeeId?: number;
    employeeCode?: string | null;
    employeeNameTh?: string | null;
    employeeNameEn?: string | null;
    periodMonth?: number;
    periodYear?: number;
    amount?: number;
    actualUsage?: number | null;
    maxAllowance?: number | null;
    status?: string | null;
    billAttachment?: string | null;
    notes?: string | null;
    approvedBy?: number | null;
    approvedByName?: string | null;
    approvedAt?: string | null;
    rejectedReason?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}

