/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for product review
 */
export interface ReviewDto { 
    id?: number;
    productId?: number;
    userId?: number;
    userName?: string;
    rating?: number;
    title?: string | null;
    comment?: string | null;
    isVerifiedPurchase?: boolean;
    helpfulCount?: number;
    status?: string;
    adminResponse?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}

