/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalaryRecordDto { 
    id?: number;
    employeeId?: number;
    employeeCode?: string | null;
    employeeNameTh?: string | null;
    employeeNameEn?: string | null;
    branchId?: number | null;
    branchName?: string | null;
    month?: number;
    year?: number;
    periodDisplay?: string | null;
    baseSalary?: number;
    daysWorked?: number;
    overtimeHours?: number;
    overtimeAmount?: number;
    totalAllowances?: number;
    phoneAllowance?: number;
    socialSecurityDeduction?: number;
    advancePaymentCurrent?: number;
    advancePaymentPrevious?: number;
    passportFeeDeduction?: number;
    taxDeduction?: number;
    otherDeductions?: number;
    leaveDays?: number;
    leaveDeduction?: number;
    totalEarnings?: number;
    totalDeductions?: number;
    netSalary?: number;
    status?: string | null;
    approvedBy?: number | null;
    approvedByName?: string | null;
    approvedAt?: string | null;
    paidAt?: string | null;
    notes?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
}

