/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShippingRateDto { 
    id?: number;
    method?: string | null;
    rate?: number;
    estimatedDays?: number;
    description?: string | null;
}

