/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateDeliveryDto { 
    scheduledDate: string;
    actualDeliveryDate?: string | null;
    driverId?: number | null;
    vehicleNumber?: string | null;
    deliveryAddress: string;
    contactPerson?: string | null;
    contactPhone?: string | null;
    status?: string | null;
    signatureUrl?: string | null;
    photoUrl?: string | null;
    notes?: string | null;
}

