/**
 * ShopErpApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for user information
 */
export interface UserDto { 
    /**
     * User ID
     */
    id?: number;
    /**
     * User\'s email address
     */
    email?: string;
    /**
     * User\'s first name
     */
    firstName?: string | null;
    /**
     * User\'s last name
     */
    lastName?: string | null;
    /**
     * User\'s full name
     */
    fullName?: string | null;
    /**
     * User\'s phone number
     */
    phone?: string | null;
    /**
     * User\'s role
     */
    role?: string | null;
    /**
     * User\'s status
     */
    status?: string | null;
    /**
     * Email verification status
     */
    emailVerified?: boolean;
    /**
     * Account creation date
     */
    createdAt?: string | null;
    /**
     * Last login date
     */
    lastLoginAt?: string | null;
}

