/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WishlistDto } from './wishlistDto';


export interface ApiResponseDtoOfListOfWishlistDto { 
    success?: boolean;
    message?: string | null;
    data?: Array<WishlistDto> | null;
    errors?: Array<string> | null;
}

