/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankAccountDto } from './bankAccountDto';


export interface ApiResponseDtoOfIEnumerableOfBankAccountDto { 
    success?: boolean;
    message?: string | null;
    data?: Array<BankAccountDto> | null;
    errors?: Array<string> | null;
}

