/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBankAccountDto { 
    branchId: number;
    bankName: string;
    accountNumber: string;
    accountName?: string | null;
    accountType?: string | null;
    initialBalance?: number | null;
}

