/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeDto { 
    id?: number;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    readonly fullName?: string | null;
    phone?: string | null;
    status?: string | null;
    role?: string | null;
    branchId?: number | null;
    branchName?: string | null;
    employeeCode?: string | null;
    position?: string | null;
    salary?: number | null;
    commissionRate?: number | null;
    hireDate?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    lastLoginAt?: string | null;
}

