/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErpSalesPaymentDto } from './erpSalesPaymentDto';
import { ErpSalesOrderItemDto } from './erpSalesOrderItemDto';


export interface ErpSalesOrderDto { 
    id?: number;
    branchId?: number;
    branchName?: string | null;
    orderNumber?: string | null;
    customerId?: number | null;
    customerName?: string | null;
    customerPhone?: string | null;
    customerAddress?: string | null;
    customerTaxId?: string | null;
    orderDate?: string;
    orderType?: string | null;
    status?: string | null;
    subtotal?: number;
    discountAmount?: number;
    discountPercentage?: number;
    amountBeforeVat?: number;
    vatEnabled?: boolean;
    vatPercentage?: number;
    vatAmount?: number;
    totalAmount?: number;
    depositAmount?: number;
    paidAmount?: number;
    outstandingAmount?: number;
    deliveryAppointmentDate?: string | null;
    deliveryDate?: string | null;
    deliveryStatus?: string | null;
    productStatus?: string | null;
    notes?: string | null;
    internalNotes?: string | null;
    createdBy?: number | null;
    createdByName?: string | null;
    updatedBy?: number | null;
    updatedByName?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    items?: Array<ErpSalesOrderItemDto> | null;
    payments?: Array<ErpSalesPaymentDto> | null;
}

