/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaterialRequisitionItemDto } from './materialRequisitionItemDto';


export interface MaterialRequisitionDto { 
    id?: number;
    requisitionNumber?: string | null;
    branchId?: number;
    branchName?: string | null;
    requestedBy?: number;
    requestedByName?: string | null;
    requisitionDate?: string;
    purpose?: string | null;
    salesOrderId?: number | null;
    salesOrderNumber?: string | null;
    status?: string | null;
    approvedBy?: number | null;
    approvedByName?: string | null;
    approvedAt?: string | null;
    notes?: string | null;
    createdAt?: string | null;
    items?: Array<MaterialRequisitionItemDto> | null;
}

