/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDto } from './productDto';


export interface WishlistDto { 
    id?: number;
    userId?: number;
    productId?: number;
    product?: ProductDto;
    createdAt?: string | null;
}

