export * from './adminCoupons.service';
import { AdminCouponsService } from './adminCoupons.service';
export * from './adminCoupons.serviceInterface';
export * from './adminOrders.service';
import { AdminOrdersService } from './adminOrders.service';
export * from './adminOrders.serviceInterface';
export * from './adminProducts.service';
import { AdminProductsService } from './adminProducts.service';
export * from './adminProducts.serviceInterface';
export * from './adminReviews.service';
import { AdminReviewsService } from './adminReviews.service';
export * from './adminReviews.serviceInterface';
export * from './adminUsers.service';
import { AdminUsersService } from './adminUsers.service';
export * from './adminUsers.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './bankAccounts.service';
import { BankAccountsService } from './bankAccounts.service';
export * from './bankAccounts.serviceInterface';
export * from './bankTransactions.service';
import { BankTransactionsService } from './bankTransactions.service';
export * from './bankTransactions.serviceInterface';
export * from './branches.service';
import { BranchesService } from './branches.service';
export * from './branches.serviceInterface';
export * from './brands.service';
import { BrandsService } from './brands.service';
export * from './brands.serviceInterface';
export * from './cart.service';
import { CartService } from './cart.service';
export * from './cart.serviceInterface';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './categories.serviceInterface';
export * from './coupons.service';
import { CouponsService } from './coupons.service';
export * from './coupons.serviceInterface';
export * from './deliveries.service';
import { DeliveriesService } from './deliveries.service';
export * from './deliveries.serviceInterface';
export * from './employeeAuth.service';
import { EmployeeAuthService } from './employeeAuth.service';
export * from './employeeAuth.serviceInterface';
export * from './employees.service';
import { EmployeesService } from './employees.service';
export * from './employees.serviceInterface';
export * from './erpCustomers.service';
import { ErpCustomersService } from './erpCustomers.service';
export * from './erpCustomers.serviceInterface';
export * from './erpSalesOrders.service';
import { ErpSalesOrdersService } from './erpSalesOrders.service';
export * from './erpSalesOrders.serviceInterface';
export * from './erpSalesPayments.service';
import { ErpSalesPaymentsService } from './erpSalesPayments.service';
export * from './erpSalesPayments.serviceInterface';
export * from './expenseCategories.service';
import { ExpenseCategoriesService } from './expenseCategories.service';
export * from './expenseCategories.serviceInterface';
export * from './expenses.service';
import { ExpensesService } from './expenses.service';
export * from './expenses.serviceInterface';
export * from './gallery.service';
import { GalleryService } from './gallery.service';
export * from './gallery.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './images.service';
import { ImagesService } from './images.service';
export * from './images.serviceInterface';
export * from './leave.service';
import { LeaveService } from './leave.service';
export * from './leave.serviceInterface';
export * from './materialRequisitions.service';
import { MaterialRequisitionsService } from './materialRequisitions.service';
export * from './materialRequisitions.serviceInterface';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders.serviceInterface';
export * from './overtime.service';
import { OvertimeService } from './overtime.service';
export * from './overtime.serviceInterface';
export * from './payroll.service';
import { PayrollService } from './payroll.service';
export * from './payroll.serviceInterface';
export * from './payrollPeriods.service';
import { PayrollPeriodsService } from './payrollPeriods.service';
export * from './payrollPeriods.serviceInterface';
export * from './payrollRecords.service';
import { PayrollRecordsService } from './payrollRecords.service';
export * from './payrollRecords.serviceInterface';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './products.serviceInterface';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './reports.serviceInterface';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './reviews.serviceInterface';
export * from './shipping.service';
import { ShippingService } from './shipping.service';
export * from './shipping.serviceInterface';
export * from './upload.service';
import { UploadService } from './upload.service';
export * from './upload.serviceInterface';
export * from './wishlist.service';
import { WishlistService } from './wishlist.service';
export * from './wishlist.serviceInterface';
export const APIS = [AdminCouponsService, AdminOrdersService, AdminProductsService, AdminReviewsService, AdminUsersService, AuthService, BankAccountsService, BankTransactionsService, BranchesService, BrandsService, CartService, CategoriesService, CouponsService, DeliveriesService, EmployeeAuthService, EmployeesService, ErpCustomersService, ErpSalesOrdersService, ErpSalesPaymentsService, ExpenseCategoriesService, ExpensesService, GalleryService, HealthService, ImagesService, LeaveService, MaterialRequisitionsService, OrdersService, OvertimeService, PayrollService, PayrollPeriodsService, PayrollRecordsService, ProductsService, ReportsService, ReviewsService, ShippingService, UploadService, WishlistService];
