/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseDtoOfBankAccountDto } from '../model/models';
import { ApiResponseDtoOfBoolean } from '../model/models';
import { ApiResponseDtoOfIEnumerableOfBankAccountDto } from '../model/models';
import { CreateBankAccountDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BankAccountsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/erp/bank-accounts/active
     */
    apiErpBankAccountsActiveGet(extraHttpRequestParams?: any): Observable<ApiResponseDtoOfIEnumerableOfBankAccountDto>;

    /**
     * 
     * 
     * @endpoint get /api/erp/bank-accounts/branch/{branchId}
     * @param branchId 
     */
    apiErpBankAccountsBranchBranchIdGet(branchId: number, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfIEnumerableOfBankAccountDto>;

    /**
     * 
     * 
     * @endpoint get /api/erp/bank-accounts
     */
    apiErpBankAccountsGet(extraHttpRequestParams?: any): Observable<ApiResponseDtoOfIEnumerableOfBankAccountDto>;

    /**
     * 
     * 
     * @endpoint delete /api/erp/bank-accounts/{id}
     * @param id 
     */
    apiErpBankAccountsIdDelete(id: number, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBoolean>;

    /**
     * 
     * 
     * @endpoint get /api/erp/bank-accounts/{id}
     * @param id 
     */
    apiErpBankAccountsIdGet(id: number, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBankAccountDto>;

    /**
     * 
     * 
     * @endpoint put /api/erp/bank-accounts/{id}
     * @param id 
     * @param createBankAccountDto 
     */
    apiErpBankAccountsIdPut(id: number, createBankAccountDto?: CreateBankAccountDto, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBankAccountDto>;

    /**
     * 
     * 
     * @endpoint post /api/erp/bank-accounts
     * @param createBankAccountDto 
     */
    apiErpBankAccountsPost(createBankAccountDto?: CreateBankAccountDto, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBankAccountDto>;

}
