/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseDtoOfBoolean } from '../model/models';
import { ApiResponseDtoOfBranchDto } from '../model/models';
import { ApiResponseDtoOfIEnumerableOfBranchDto } from '../model/models';
import { CreateBranchDto } from '../model/models';
import { UpdateBranchDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BranchesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/erp/branches/active
     */
    apiErpBranchesActiveGet(extraHttpRequestParams?: any): Observable<ApiResponseDtoOfIEnumerableOfBranchDto>;

    /**
     * 
     * 
     * @endpoint get /api/erp/branches/code/{code}
     * @param code 
     */
    apiErpBranchesCodeCodeGet(code: string, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBranchDto>;

    /**
     * 
     * 
     * @endpoint get /api/erp/branches
     */
    apiErpBranchesGet(extraHttpRequestParams?: any): Observable<ApiResponseDtoOfIEnumerableOfBranchDto>;

    /**
     * 
     * 
     * @endpoint delete /api/erp/branches/{id}
     * @param id 
     */
    apiErpBranchesIdDelete(id: number, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBoolean>;

    /**
     * 
     * 
     * @endpoint get /api/erp/branches/{id}
     * @param id 
     */
    apiErpBranchesIdGet(id: number, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBranchDto>;

    /**
     * 
     * 
     * @endpoint put /api/erp/branches/{id}
     * @param id 
     * @param updateBranchDto 
     */
    apiErpBranchesIdPut(id: number, updateBranchDto?: UpdateBranchDto, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBranchDto>;

    /**
     * 
     * 
     * @endpoint post /api/erp/branches/{id}/set-main
     * @param id 
     */
    apiErpBranchesIdSetMainPost(id: number, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBoolean>;

    /**
     * 
     * 
     * @endpoint get /api/erp/branches/main
     */
    apiErpBranchesMainGet(extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBranchDto>;

    /**
     * 
     * 
     * @endpoint post /api/erp/branches
     * @param createBranchDto 
     */
    apiErpBranchesPost(createBranchDto?: CreateBranchDto, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfBranchDto>;

}
