/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateDeliveryDto } from '../model/models';
import { DeliveryDto } from '../model/models';
import { UpdateDeliveryDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DeliveriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/erp/deliveries/branch/{branchId}
     * @param branchId 
     */
    apiErpDeliveriesBranchBranchIdGet(branchId: number, extraHttpRequestParams?: any): Observable<Array<DeliveryDto>>;

    /**
     * 
     * 
     * @endpoint get /api/erp/deliveries/driver/{driverId}
     * @param driverId 
     */
    apiErpDeliveriesDriverDriverIdGet(driverId: number, extraHttpRequestParams?: any): Observable<Array<DeliveryDto>>;

    /**
     * 
     * 
     * @endpoint get /api/erp/deliveries
     */
    apiErpDeliveriesGet(extraHttpRequestParams?: any): Observable<Array<DeliveryDto>>;

    /**
     * 
     * 
     * @endpoint delete /api/erp/deliveries/{id}
     * @param id 
     */
    apiErpDeliveriesIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/erp/deliveries/{id}
     * @param id 
     */
    apiErpDeliveriesIdGet(id: number, extraHttpRequestParams?: any): Observable<DeliveryDto>;

    /**
     * 
     * 
     * @endpoint put /api/erp/deliveries/{id}
     * @param id 
     * @param updateDeliveryDto 
     */
    apiErpDeliveriesIdPut(id: number, updateDeliveryDto?: UpdateDeliveryDto, extraHttpRequestParams?: any): Observable<DeliveryDto>;

    /**
     * 
     * 
     * @endpoint post /api/erp/deliveries
     * @param createDeliveryDto 
     */
    apiErpDeliveriesPost(createDeliveryDto?: CreateDeliveryDto, extraHttpRequestParams?: any): Observable<DeliveryDto>;

    /**
     * 
     * 
     * @endpoint get /api/erp/deliveries/status/{status}
     * @param status 
     */
    apiErpDeliveriesStatusStatusGet(status: string, extraHttpRequestParams?: any): Observable<Array<DeliveryDto>>;

}
