/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateErpCustomerDto } from '../model/models';
import { ErpCustomerDto } from '../model/models';
import { UpdateErpCustomerDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ErpCustomersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/erp/customers
     */
    apiErpCustomersGet(extraHttpRequestParams?: any): Observable<Array<ErpCustomerDto>>;

    /**
     * 
     * 
     * @endpoint delete /api/erp/customers/{id}
     * @param id 
     */
    apiErpCustomersIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/erp/customers/{id}
     * @param id 
     */
    apiErpCustomersIdGet(id: number, extraHttpRequestParams?: any): Observable<ErpCustomerDto>;

    /**
     * 
     * 
     * @endpoint put /api/erp/customers/{id}
     * @param id 
     * @param updateErpCustomerDto 
     */
    apiErpCustomersIdPut(id: number, updateErpCustomerDto?: UpdateErpCustomerDto, extraHttpRequestParams?: any): Observable<ErpCustomerDto>;

    /**
     * 
     * 
     * @endpoint post /api/erp/customers
     * @param createErpCustomerDto 
     */
    apiErpCustomersPost(createErpCustomerDto?: CreateErpCustomerDto, extraHttpRequestParams?: any): Observable<ErpCustomerDto>;

    /**
     * 
     * 
     * @endpoint get /api/erp/customers/type/{customerType}
     * @param customerType 
     */
    apiErpCustomersTypeCustomerTypeGet(customerType: string, extraHttpRequestParams?: any): Observable<Array<ErpCustomerDto>>;

}
