/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseDtoOfImageUploadResultDto } from '../model/models';
import { ApiResponseDtoOfObject } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ImagesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/images/{fileName}
     * @param fileName 
     */
    apiImagesFileNameDelete(fileName: string, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfObject>;

    /**
     * 
     * 
     * @endpoint post /api/images/upload
     * @param file 
     */
    apiImagesUploadPost(file?: Blob, extraHttpRequestParams?: any): Observable<ApiResponseDtoOfImageUploadResultDto>;

}
