/**
 * ShopErpApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReportsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/reports/brands/excel
     */
    apiReportsBrandsExcelGet(extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/brands/pdf
     */
    apiReportsBrandsPdfGet(extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/categories/excel
     */
    apiReportsCategoriesExcelGet(extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/categories/pdf
     */
    apiReportsCategoriesPdfGet(extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/coupons/excel
     * @param activeOnly 
     */
    apiReportsCouponsExcelGet(activeOnly?: boolean, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/coupons/pdf
     * @param activeOnly 
     */
    apiReportsCouponsPdfGet(activeOnly?: boolean, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/orders/excel
     * @param startDate 
     * @param endDate 
     * @param status 
     */
    apiReportsOrdersExcelGet(startDate?: string, endDate?: string, status?: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/orders/{id}/invoice
     * @param id 
     */
    apiReportsOrdersIdInvoiceGet(id: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/orders/{id}/invoice/thermal
     * @param id 
     */
    apiReportsOrdersIdInvoiceThermalGet(id: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/orders/{id}/pdf
     * @param id 
     */
    apiReportsOrdersIdPdfGet(id: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/orders/{id}/pdf/thermal
     * @param id 
     */
    apiReportsOrdersIdPdfThermalGet(id: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/orders/pdf
     * @param startDate 
     * @param endDate 
     * @param status 
     */
    apiReportsOrdersPdfGet(startDate?: string, endDate?: string, status?: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/payroll/salary-records/{id}/pay-slip
     * @param id 
     */
    apiReportsPayrollSalaryRecordsIdPaySlipGet(id: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/products/excel
     * @param categoryId 
     * @param brandId 
     */
    apiReportsProductsExcelGet(categoryId?: number, brandId?: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/products/pdf
     * @param categoryId 
     * @param brandId 
     */
    apiReportsProductsPdfGet(categoryId?: number, brandId?: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/reviews/excel
     * @param minRating 
     * @param maxRating 
     */
    apiReportsReviewsExcelGet(minRating?: number, maxRating?: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/reviews/pdf
     * @param minRating 
     * @param maxRating 
     */
    apiReportsReviewsPdfGet(minRating?: number, maxRating?: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/users/excel
     * @param role 
     */
    apiReportsUsersExcelGet(role?: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint get /api/reports/users/pdf
     * @param role 
     */
    apiReportsUsersPdfGet(role?: string, extraHttpRequestParams?: any): Observable<Blob>;

}
