import { Product, Category, Brand, ProductVariant, ProductImage } from '../models/product.model';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'สีทาอาคาร',
    slug: 'building-paint',
    description: 'สีทาอาคารทุกประเภท',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 2,
    parentId: 1,
    name: 'สีทาภายใน',
    slug: 'interior-paint',
    description: 'สีทาภายในบ้าน',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 3,
    parentId: 1,
    name: 'สีทาภายนอก',
    slug: 'exterior-paint',
    description: 'สีทาภายนอกอาคาร',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 4,
    parentId: 1,
    name: 'สีทาหลังคา',
    slug: 'roof-paint',
    description: 'สีทาหลังคาและสนามกีฬา',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 5,
    name: 'สีรองพื้น',
    slug: 'primer',
    description: 'สีรองพื้นสำหรับเตรียมผิว',
    displayOrder: 4,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 6,
    name: 'สีโป๊ว',
    slug: 'putty',
    description: 'สีโป๊วปรับผิวเรียบ',
    displayOrder: 5,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 7,
    name: 'ทินเนอร์',
    slug: 'thinner',
    description: 'ทินเนอร์และน้ำยาทำความสะอาด',
    displayOrder: 6,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 8,
    name: 'แลกเกอร์',
    slug: 'lacquer',
    description: 'แลกเกอร์เคลือบเงา',
    displayOrder: 7,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 9,
    name: 'ยาขัด',
    slug: 'polishing-compound',
    description: 'ยาขัดเงาและขัดเคลือบ',
    displayOrder: 8,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 10,
    name: 'น้ำยาเกาะพลาสติก',
    slug: 'plastic-adhesive',
    description: 'น้ำยาเพิ่มความเกาะพลาสติก',
    displayOrder: 9,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 11,
    name: 'น้ำยาเช็ดคราบ',
    slug: 'stain-remover',
    description: 'น้ำยาเช็ดทำความสะอาดคราบสี',
    displayOrder: 10,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 12,
    name: 'สีเบอร์รถยนต์',
    slug: 'automotive-paint',
    description: 'สีสำหรับรถยนต์และยานพาหนะ',
    displayOrder: 11,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 13,
    name: 'สีสเปเชี่ยวของร้าน',
    slug: 'special-paint',
    description: 'สีพิเศษและสีผสมตามสั่ง',
    displayOrder: 12,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 14,
    name: 'อุปกรณ์สำหรับช่างสี',
    slug: 'paint-tools',
    description: 'แปรง โรลเลอร์ และอุปกรณ์ช่างสี',
    displayOrder: 13,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const MOCK_BRANDS: Brand[] = [
  {
    id: 1,
    name: 'TOA',
    slug: 'toa',
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBmeDWEhBCSnRvlCxtlHei6egQklbH58JupmyWdAM-FA&s',
    description: 'แบรนด์สีชั้นนำของไทย',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 2,
    name: 'Nippon Paint',
    slug: 'nippon-paint',
    logoUrl: 'https://www.acbengineering.co.th/wp-content/uploads/2018/09/nipponpaint_logo.jpg',
    description: 'สีคุณภาพสูงจากญี่ปุ่น',
    isActive: true,
    displayOrder: 2,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 3,
    name: 'Jotun',
    slug: 'jotun',
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSCPJ-O6a5qmsBSEwf3btKsLGDzjPPXHviI35pSFtIvQrHOLN73PAVEBfe&s=10',
    description: 'สีจากนอร์เวย์',
    isActive: true,
    displayOrder: 3,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 4,
    name: 'Dulux',
    slug: 'dulux',
    logoUrl: 'https://i.pinimg.com/736x/5a/48/06/5a480695ca600b0098f7589cf8f46157.jpg',
    description: 'สีคุณภาพจาก ICI',
    isActive: true,
    displayOrder: 4,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 5,
    name: 'Captain',
    slug: 'captain',
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLBLLOMJdZtH5U9Z6hRPOQ7VNcjnckULCrwBdQsQXRdnco2cSkdwoXTnrI&s=10',
    description: 'สีทาหลังคาคุณภาพ',
    isActive: true,
    displayOrder: 5,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    categoryId: 2,
    brandId: 1,
    sku: 'TOA-SM-BASE',
    name: 'TOA Supermatex ทีโอเอ ซุปเปอร์เมเทค',
    slug: 'toa-supermatex',
    shortDescription: 'สีน้ำอะครีลิคสำหรับทาภายใน ผิวด้าน ทนทานเกรดพรีเมียม',
    fullDescription: 'TOA Supermatex เป็นสีน้ำอะครีลิคคุณภาพสูง สำหรับทาภายในอาคาร มีผิวสัมผัสเนียนนุ่ม ทาง่าย เกลี่ยได้ดี ให้ผิวสีเรียบสวย เนื้อสีเข้มข้น ทำให้สีคงทน ไม่จางหายง่าย',
    features: [
      'ผิวสีเรียบสวย ด้าน',
      'ทาง่าย เกลี่ยได้ดี',
      'เนื้อสีเข้มข้น ทำให้สีคงทน',
      'ปกปิดได้ดี',
      'ไม่มีกลิ่นฉุน',
      'ผ่านมาตรฐาน มอก. 2321-2564',
    ],
    specifications: {
      type: 'สีน้ำอะครีลิค',
      finish: 'ด้าน (Matte)',
      base: 'น้ำ (Water-based)',
      coverage: '10-12 ตร.ม./ลิตร/ชั้น',
      dryTime: 'แห้งสนิท 2-4 ชั่วโมง',
      recoatTime: 'ทาซ้ำได้ใน 4-6 ชั่วโมง',
    },
    usageInstructions: '1. เตรียมผิวให้สะอาด แห้ง และเรียบ\n2. ทารองพื้นก่อน (แนะนำ TOA Quick Coat)\n3. คนสีให้เข้ากันก่อนทา\n4. ทาอย่างน้อย 2 ชั้น',
    warnings: 'เก็บให้พ้นมือเด็ก ใช้ในที่อากาศถ่ายเท ห้ามรับประทาน',
    standardCertification: 'มอก. 2321-2564',
    coverageAreaPerLiter: 11,
    basePrice: 299,
    compareAtPrice: 350,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    isActive: true,
    averageRating: 4.5,
    reviewCount: 128,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 2,
    categoryId: 3,
    brandId: 1,
    sku: 'TOA-4S-BASE',
    name: 'TOA 4Seasons 2in1 Exterior Matt',
    slug: 'toa-4seasons-2in1',
    shortDescription: 'สีทาภายนอก 2 in 1 รองพื้น+สีทา ในขั้นตอนเดียว',
    fullDescription: 'TOA 4Seasons 2in1 เป็นสีทาภายนอกคุณภาพสูง ผสมรองพื้นและสีทาไว้ในตัว ลดขั้นตอนการทำงาน ทนทานต่อแสงแดดและฝน มีฟิล์มยืดหยุ่น ไม่แตกร้าว',
    features: [
      'รองพื้น+สีทา 2 in 1',
      'ทนทานต่อแสงแดดและฝน',
      'ฟิล์มยืดหยุ่น ไม่แตกร้าว',
      'ป้องกัน UV',
      'กันเชื้อราและสาหร่าย',
      'ประหยัดเวลา ลดขั้นตอน',
    ],
    specifications: {
      type: 'สีน้ำอะครีลิค 2in1',
      finish: 'ด้าน (Matt)',
      base: 'น้ำ (Water-based)',
      coverage: '8-10 ตร.ม./ลิตร/ชั้น',
      dryTime: 'แห้งสนิท 3-4 ชั่วโมง',
      recoatTime: 'ทาซ้ำได้ใน 6-8 ชั่วโมง',
    },
    basePrice: 450,
    compareAtPrice: 520,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 95,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 3,
    categoryId: 2,
    brandId: 2,
    sku: 'NP-QC-BASE',
    name: 'NIPPON PAINT Quick Coat รองพื้นปูนใหม่',
    slug: 'nippon-quick-coat',
    shortDescription: 'รองพื้นปูนใหม่ ทนความชื้นสูง ลดเวลารอ',
    fullDescription: 'Nippon Paint Quick Coat เป็นรองพื้นสูตรพิเศษ สำหรับปูนใหม่ที่มีความชื้นสูงถึง 40% ช่วยลดเวลารอให้ปูนแห้ง ป้องกันปัญหาฟอง ลอก และด่างขึ้นผิว',
    features: [
      'ทนความชื้นสูงถึง 40%',
      'ลดเวลารอ ประหยัดเวลา',
      'ป้องกันฟอง ลอก',
      'ป้องกันด่างขึ้นผิว',
      'เพิ่มการยึดเกาะของสี',
      'ทาง่าย แห้งเร็ว',
    ],
    specifications: {
      type: 'รองพื้นปูนใหม่',
      finish: 'ด้าน',
      base: 'น้ำ (Water-based)',
      coverage: '10-12 ตร.ม./ลิตร',
      dryTime: 'แห้งสนิท 2 ชั่วโมง',
      moistureTolerance: 'สูงถึง 40%',
    },
    basePrice: 380,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 72,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 4,
    categoryId: 4,
    brandId: 5,
    sku: 'CAP-RF-BASE',
    name: 'CAPTAIN ROOF PAINT สีทาหลังคา',
    slug: 'captain-roof-paint',
    shortDescription: 'สีทาหลังคาและสนามกีฬา ทนแดด ทนฝน มอก. 2321-2564',
    fullDescription: 'Captain Roof Paint สีอะครีลิกสำหรับทาภายนอก มีคุณสมบัติพิเศษในการทนต่อสภาพอากาศ ทนแดด ทนฝน ให้ฟิล์มที่แข็งแรง ยืดหยุ่น ไม่แตกร้าว ไม่ลอกง่าย ทนต่อรังสี UV ทำให้สีคงทน',
    features: [
      'ทนแดด ทนฝน',
      'ฟิล์มแข็งแรง ยืดหยุ่น',
      'ไม่แตกร้าว ไม่ลอก',
      'ทน UV สีคงทน',
      'ผิวด้าน ลดแสงสะท้อน',
      'เหมาะสำหรับหลังคาและสนามกีฬา',
      'ผ่านมาตรฐาน มอก. 2321-2564',
    ],
    specifications: {
      type: 'สีอะครีลิกทาหลังคา',
      finish: 'ด้าน (Matte)',
      base: 'น้ำ (Water-based)',
      coverage: '7-9 ตร.ม./ลิตร/ชั้น',
      dryTime: 'แห้งสนิท 4 ชั่วโมง',
      recoatTime: 'ทาซ้ำได้ใน 8 ชั่วโมง',
    },
    standardCertification: 'มอก. 2321-2564',
    basePrice: 320,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    isActive: true,
    averageRating: 4.4,
    reviewCount: 45,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
];

// Generate variants for each product
export const MOCK_VARIANTS: ProductVariant[] = [
  // TOA Supermatex variants
  {
    id: 1,
    productId: 1,
    sku: 'TOA-SM-1L-WHT',
    name: '1 ลิตร - สีขาว',
    sizeValue: 1,
    sizeUnit: 'ลิตร',
    colorName: 'สีขาว',
    colorCode: '#FFFFFF',
    price: 299,
    compareAtPrice: 350,
    stockQuantity: 150,
    lowStockThreshold: 20,
    weight: 1.2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    productId: 1,
    sku: 'TOA-SM-GL-WHT',
    name: 'แกลลอน (3.785 ลิตร) - สีขาว',
    sizeValue: 3.785,
    sizeUnit: 'ลิตร',
    colorName: 'สีขาว',
    colorCode: '#FFFFFF',
    price: 999,
    compareAtPrice: 1200,
    stockQuantity: 80,
    lowStockThreshold: 15,
    weight: 4.5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    productId: 1,
    sku: 'TOA-SM-18L-WHT',
    name: 'ถัง (18 ลิตร) - สีขาว',
    sizeValue: 18,
    sizeUnit: 'ลิตร',
    colorName: 'สีขาว',
    colorCode: '#FFFFFF',
    price: 4500,
    compareAtPrice: 5200,
    stockQuantity: 45,
    lowStockThreshold: 10,
    weight: 21,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // TOA 4Seasons variants
  {
    id: 4,
    productId: 2,
    sku: 'TOA-4S-GL-WHT',
    name: 'แกลลอน (3.785 ลิตร) - สีขาว',
    sizeValue: 3.785,
    sizeUnit: 'ลิตร',
    colorName: 'สีขาว',
    colorCode: '#FFFFFF',
    price: 1450,
    compareAtPrice: 1680,
    stockQuantity: 60,
    lowStockThreshold: 15,
    weight: 4.5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    productId: 2,
    sku: 'TOA-4S-18L-WHT',
    name: 'ถัง (18 ลิตร) - สีขาว',
    sizeValue: 18,
    sizeUnit: 'ลิตร',
    colorName: 'สีขาว',
    colorCode: '#FFFFFF',
    price: 6500,
    stockQuantity: 35,
    lowStockThreshold: 10,
    weight: 21,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Nippon Quick Coat variants
  {
    id: 6,
    productId: 3,
    sku: 'NP-QC-2.5L',
    name: '2.5 ลิตร',
    sizeValue: 2.5,
    sizeUnit: 'ลิตร',
    price: 850,
    stockQuantity: 70,
    lowStockThreshold: 15,
    weight: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    productId: 3,
    sku: 'NP-QC-9L',
    name: '9 ลิตร',
    sizeValue: 9,
    sizeUnit: 'ลิตร',
    price: 2800,
    stockQuantity: 40,
    lowStockThreshold: 10,
    weight: 10.5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Captain Roof Paint variants
  {
    id: 8,
    productId: 4,
    sku: 'CAP-RF-GL-RED',
    name: 'แกลลอน - สีแดง',
    sizeValue: 3.785,
    sizeUnit: 'ลิตร',
    colorName: 'สีแดง',
    colorCode: '#C41E3A',
    price: 1080,
    stockQuantity: 55,
    lowStockThreshold: 15,
    weight: 4.5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    productId: 4,
    sku: 'CAP-RF-GL-GRN',
    name: 'แกลลอน - สีเขียว',
    sizeValue: 3.785,
    sizeUnit: 'ลิตร',
    colorName: 'สีเขียว',
    colorCode: '#228B22',
    price: 1080,
    stockQuantity: 48,
    lowStockThreshold: 15,
    weight: 4.5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Generate images for products
export const MOCK_IMAGES: ProductImage[] = [
  // TOA Supermatex images
  { id: 1, productId: 1, imageUrl: 'https://via.placeholder.com/600x600?text=TOA+Supermatex+1', isPrimary: true, displayOrder: 1, createdAt: new Date() },
  { id: 2, productId: 1, imageUrl: 'https://via.placeholder.com/600x600?text=TOA+Supermatex+2', isPrimary: false, displayOrder: 2, createdAt: new Date() },
  { id: 3, productId: 1, imageUrl: 'https://via.placeholder.com/600x600?text=TOA+Supermatex+3', isPrimary: false, displayOrder: 3, createdAt: new Date() },

  // TOA 4Seasons images
  { id: 4, productId: 2, imageUrl: 'https://via.placeholder.com/600x600?text=TOA+4Seasons+1', isPrimary: true, displayOrder: 1, createdAt: new Date() },
  { id: 5, productId: 2, imageUrl: 'https://via.placeholder.com/600x600?text=TOA+4Seasons+2', isPrimary: false, displayOrder: 2, createdAt: new Date() },

  // Nippon Quick Coat images
  { id: 6, productId: 3, imageUrl: 'https://via.placeholder.com/600x600?text=Nippon+Quick+Coat+1', isPrimary: true, displayOrder: 1, createdAt: new Date() },
  { id: 7, productId: 3, imageUrl: 'https://via.placeholder.com/600x600?text=Nippon+Quick+Coat+2', isPrimary: false, displayOrder: 2, createdAt: new Date() },

  // Captain Roof Paint images
  { id: 8, productId: 4, imageUrl: 'https://via.placeholder.com/600x600?text=Captain+Roof+Paint+1', isPrimary: true, displayOrder: 1, createdAt: new Date() },
  { id: 9, productId: 4, imageUrl: 'https://via.placeholder.com/600x600?text=Captain+Roof+Paint+2', isPrimary: false, displayOrder: 2, createdAt: new Date() },
];

// Combine products with their variants and images
export function getMockProductsWithDetails(): Product[] {
  return MOCK_PRODUCTS.map(product => ({
    ...product,
    category: MOCK_CATEGORIES.find(c => c.id === product.categoryId),
    brand: MOCK_BRANDS.find(b => b.id === product.brandId),
    variants: MOCK_VARIANTS.filter(v => v.productId === product.id),
    images: MOCK_IMAGES.filter(i => i.productId === product.id),
  }));
}
